Repository ArcadeData/arcadedb, pull requests merged in 2023-11, with the labels that each got.

#1294 update pre-commit hook versions
  .pre-commit-config.yaml
Labels: dependencies, dependency_approved

#1295 Add english locale to case conversions
  .pre-commit-config.yaml
  console/src/main/java/com/arcadedb/console/Console.java
  engine/src/main/java/com/arcadedb/ContextConfiguration.java
  engine/src/main/java/com/arcadedb/GlobalConfiguration.java
  engine/src/main/java/com/arcadedb/index/vector/distance/DistanceFunctionFactory.java
  engine/src/main/java/com/arcadedb/query/QueryEngineManager.java
  engine/src/main/java/com/arcadedb/query/select/SelectOperator.java
  engine/src/main/java/com/arcadedb/query/sql/executor/CastToStepAbstract.java
  engine/src/main/java/com/arcadedb/query/sql/executor/FetchFromSchemaDatabaseStep.java
  engine/src/main/java/com/arcadedb/query/sql/method/DefaultSQLMethodFactory.java
  engine/src/main/java/com/arcadedb/query/sql/method/string/SQLMethodCapitalize.java
  engine/src/main/java/com/arcadedb/query/sql/method/string/SQLMethodToLowerCase.java
  engine/src/main/java/com/arcadedb/query/sql/parser/AlterPropertyStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/AlterTypeStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/BeginStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/ILikeOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/MethodCall.java
  engine/src/main/java/com/arcadedb/schema/Property.java
  engine/src/main/java/com/arcadedb/schema/Type.java
  engine/src/main/java/com/arcadedb/utility/AnsiCode.java
  graphql/src/main/java/com/arcadedb/graphql/schema/GraphQLSchema.java
  gremlin/src/main/java/com/arcadedb/gremlin/ArcadeFilterByIndexStep.java
  gremlin/src/main/java/com/arcadedb/gremlin/ArcadeFilterByTypeStep.java
  integration/src/main/java/com/arcadedb/integration/backup/Backup.java
  integration/src/main/java/com/arcadedb/integration/backup/BackupSettings.java
  integration/src/main/java/com/arcadedb/integration/exporter/Exporter.java
  integration/src/main/java/com/arcadedb/integration/exporter/ExporterSettings.java
  integration/src/main/java/com/arcadedb/integration/importer/Neo4jImporter.java
  integration/src/main/java/com/arcadedb/integration/importer/format/CSVImporterFormat.java
  integration/src/main/java/com/arcadedb/integration/importer/format/JSONImporterFormat.java
  integration/src/main/java/com/arcadedb/integration/importer/vector/TextEmbeddingsImporter.java
  integration/src/main/java/com/arcadedb/integration/restore/Restore.java
  integration/src/main/java/com/arcadedb/integration/restore/RestoreSettings.java
  network/src/main/java/com/arcadedb/remote/RemoteVertex.java
  postgresw/src/main/java/com/arcadedb/postgres/PostgresNetworkExecutor.java
  redisw/src/main/java/com/arcadedb/redis/RedisNetworkExecutor.java
  server/src/main/java/com/arcadedb/server/ArcadeDBServer.java
  server/src/main/java/com/arcadedb/server/ha/HAServer.java
  server/src/main/java/com/arcadedb/server/ha/ReplicatedDatabase.java
  server/src/main/java/com/arcadedb/server/http/handler/GetServerHandler.java
  server/src/main/java/com/arcadedb/server/http/handler/PostCommandHandler.java
  server/src/main/java/com/arcadedb/server/http/handler/PostServerCommandHandler.java
  server/src/main/java/com/arcadedb/server/http/ws/ChangeEvent.java
  server/src/main/java/com/arcadedb/server/http/ws/WebSocketReceiveListener.java
Labels: bug, fixed

#1298 Add test for two empty strings in binary comparator
  engine/src/main/java/com/arcadedb/serializer/BinaryComparator.java
Labels: bug

#1326 feat: awaitRespsonse for HTTP command
  server/src/main/java/com/arcadedb/server/http/handler/PostCommandHandler.java
  server/src/test/java/com/arcadedb/server/HTTPDocumentIT.java
Labels: enhancement

#1332 fix: Add missing option to env var in Dockerfiles
  package/src/main/docker/Dockerfile
  package/src/main/docker/Dockerfile-multi
Labels: bug
