Repository ArcadeData/arcadedb, pull requests merged in 2023-03, with the labels that each got.

#923 [Snyk] Upgrade io.undertow:undertow-core from 2.3.3.Final to 2.3.4.Final
  server/pom.xml
Labels: dependencies

#672 [Snyk] Upgrade de.bwaldvogel:mongo-java-server from 1.41.0 to 1.42.0
  mongodbw/pom.xml
Labels: dependencies, dependency_approved

#949 update maven wrapper, maven version
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: enhancement, dependencies

#987 Add readonly default server group
  package/src/main/config/server-groups.json
Labels: enhancement
