Repository ArcadeData/arcadedb, pull requests merged in 2023-05, with the labels that each got.

#1067 Change JVM version string
  server/src/main/java/com/arcadedb/server/ArcadeDBServer.java
Labels: enhancement

#1081 ensure banner is flushed
  package/src/main/scripts/server.sh
Labels: bug

#1082 [Snyk] Upgrade io.netty:netty-transport from 4.1.86.Final to 4.1.92.Final
  mongodbw/pom.xml
Labels: dependency_approved
