Repository ArcadeData/arcadedb, pull requests merged in 2024-05, with the labels that each got.

#1555 #1553 split gremlin in shaded and standard jar
  gremlin/pom.xml
  mongodbw/pom.xml
  package/pom.xml
  pom.xml
  postgresw/pom.xml
  redisw/pom.xml
Labels: enhancement

#1584 feat: add SQL join method
  engine/src/main/java/com/arcadedb/query/sql/method/DefaultSQLMethodFactory.java
  engine/src/main/java/com/arcadedb/query/sql/method/collection/SQLMethodJoin.java
Labels: enhancement

#1585 rewrite MethodJoin and add test
  engine/src/main/java/com/arcadedb/query/sql/method/collection/SQLMethodJoin.java
  engine/src/test/java/com/arcadedb/query/sql/method/collection/SQLMethodJoinTest.java
Labels: documentation, enhancement

#1583 fix: comparison of empty strings with like
  engine/src/main/java/com/arcadedb/query/sql/executor/QueryHelper.java
  engine/src/test/java/com/arcadedb/query/sql/parser/operators/ILikeOperatorTest.java
  engine/src/test/java/com/arcadedb/query/sql/parser/operators/LikeOperatorTest.java
Labels: enhancement

#1604 Fix missing HTTP Post language guard
  server/src/main/java/com/arcadedb/server/http/handler/PostCommandHandler.java
Labels: enhancement

#1611 fix: create property default value assignment
  engine/src/main/java/com/arcadedb/query/sql/parser/CreatePropertyAttributeStatement.java
Labels: bug
