Repository ArcadeData/arcadedb, pull requests merged in 2024-12, with the labels that each got.

#1849 Fixed html injection based on node content
  studio/src/main/resources/static/js/studio-graph-widget.js
Labels: bug, security

#1852 feat: disable backup lock for embedded massive insertion only gaining…
  engine/src/main/java/com/arcadedb/GlobalConfiguration.java
  engine/src/main/java/com/arcadedb/database/LocalDatabase.java
  engine/src/main/java/com/arcadedb/utility/RWLockContext.java
  engine/src/test/java/performance/LocalDatabaseBenchmark.java
Labels: enhancement, performance

#1853 Centralized page manager
  engine/src/main/java/com/arcadedb/GlobalConfiguration.java
  engine/src/main/java/com/arcadedb/Profiler.java
  engine/src/main/java/com/arcadedb/database/DatabaseComparator.java
  engine/src/main/java/com/arcadedb/database/DatabaseFactory.java
  engine/src/main/java/com/arcadedb/database/LocalDatabase.java
  engine/src/main/java/com/arcadedb/database/RID.java
  engine/src/main/java/com/arcadedb/database/TransactionContext.java
  engine/src/main/java/com/arcadedb/database/async/DatabaseAsyncExecutorImpl.java
  engine/src/main/java/com/arcadedb/engine/BasePage.java
  engine/src/main/java/com/arcadedb/engine/BucketIterator.java
  engine/src/main/java/com/arcadedb/engine/CachedPage.java
  engine/src/main/java/com/arcadedb/engine/Dictionary.java
  engine/src/main/java/com/arcadedb/engine/ImmutablePage.java
  engine/src/main/java/com/arcadedb/engine/LocalBucket.java
  engine/src/main/java/com/arcadedb/engine/MutablePage.java
  engine/src/main/java/com/arcadedb/engine/PageId.java
  engine/src/main/java/com/arcadedb/engine/PageManager.java
  engine/src/main/java/com/arcadedb/engine/PageManagerFlushThread.java
  engine/src/main/java/com/arcadedb/engine/TransactionManager.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndex.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndexAbstract.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndexCompacted.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndexCompactor.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndexCursor.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndexDebugger.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndexMutable.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndexUnderlyingCompactedSeriesCursor.java
  engine/src/main/java/com/arcadedb/schema/LocalSchema.java
  engine/src/test/java/com/arcadedb/ACIDTransactionTest.java
  engine/src/test/java/com/arcadedb/LargeRecordsTest.java
  engine/src/test/java/com/arcadedb/PageManagerStressTest.java
  engine/src/test/java/com/arcadedb/database/CheckDatabaseTest.java
  engine/src/test/java/com/arcadedb/graph/TestVertexDelete.java
  engine/src/test/java/com/arcadedb/query/sql/executor/ScriptExecutionTest.java
  engine/src/test/java/performance/PerformanceTest.java
  integration/src/main/java/com/arcadedb/integration/backup/format/FullBackupFormat.java
  server/src/main/java/com/arcadedb/server/ha/ReplicatedDatabase.java
  server/src/main/java/com/arcadedb/server/ha/message/DatabaseAlignRequest.java
  server/src/main/java/com/arcadedb/server/ha/message/DatabaseChangeStructureRequest.java
  server/src/main/java/com/arcadedb/server/ha/message/FileContentRequest.java
  server/src/main/java/com/arcadedb/server/ha/message/FileContentResponse.java
Labels: enhancement

#1856 fix: supported SQL size() on records #1855
  engine/src/main/java/com/arcadedb/database/BaseRecord.java
  engine/src/main/java/com/arcadedb/database/Record.java
  engine/src/main/java/com/arcadedb/query/sql/method/collection/SQLMethodSize.java
  engine/src/test/java/com/arcadedb/query/sql/function/sql/SQLFunctionsTest.java
Labels: enhancement

#1860 fix: supported IPV6 in HA configuration
  gremlin/src/main/java/com/arcadedb/gremlin/ArcadeGraph.java
  network/src/main/java/com/arcadedb/network/HostUtil.java
  network/src/main/java/com/arcadedb/remote/RemoteHttpComponent.java
  network/src/test/java/com/arcadedb/HostUtilTest.java
  server/src/main/java/com/arcadedb/server/ha/HAServer.java
  server/src/main/java/com/arcadedb/server/ha/Replica2LeaderNetworkExecutor.java
  server/src/test/java/com/arcadedb/server/ha/HARandomCrashIT.java
  server/src/test/java/com/arcadedb/server/ha/HASplitBrainIT.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerLeaderChanges3TimesIT.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerLeaderDownIT.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerLeaderDownNoTransactionsToForwardIT.java
  server/src/test/java/com/arcadedb/server/security/ServerProfilingIT.java
Labels: bug

#1692 Improve console batch mode
  console/pom.xml
  console/src/main/java/com/arcadedb/console/Console.java
  console/src/test/java/com/arcadedb/console/ConsoleBatchTest.java
Labels: enhancement
