Repository ArcadeData/arcadedb, pull requests merged in 2024-10, with the labels that each got.

#1758 fix: re-enable pre-commit
  .github/workflows/mvn-deploy.yml
  .github/workflows/mvn-test.yml
Labels: bug, fixed

#1768 Fix code scanning alert no. 45: Implicit narrowing conversion in compound assignment
  console/src/test/java/com/arcadedb/console/ConsoleTest.java
Labels: fixed

#1767 #1756 add upload SARIF to workflow
  .github/workflows/meterian.yml
Labels: enhancement

#1769 Fix code scanning alert no. 86: Client-side cross-site scripting
  studio/src/main/resources/static/query.html
Labels: enhancement

#1757 #1756 migrate build and runtime in docker file to java 17
  .github/workflows/mvn-deploy.yml
  .github/workflows/mvn-release.yml
  .github/workflows/mvn-test.yml
  package/src/main/docker/Dockerfile
  pom.xml
  studio/pom.xml
Labels: enhancement, java

#1501 feat: implement ALTER TYPE oldName NAME newName operation
  engine/src/main/java/com/arcadedb/query/sql/parser/AlterTypeStatement.java
  engine/src/test/java/com/arcadedb/query/sql/executor/AlterTypeExecutionTest.java
Labels: enhancement

#1782 #1781 remove CodeQL workflow in favor
  .github/workflows/codeql-analysis.yml
Labels: fixed

#1790 Refactor "map2json"
  engine/src/main/java/com/arcadedb/database/BaseDocument.java
  engine/src/main/java/com/arcadedb/database/JSONSerializer.java
  engine/src/main/java/com/arcadedb/database/MutableDocument.java
Labels: enhancement

#1794 Fixed issue on creating a replicated database
  engine/src/main/java/com/arcadedb/database/JSONSerializer.java
  server/src/main/java/com/arcadedb/server/event/FileServerEventLog.java
  server/src/main/java/com/arcadedb/server/ha/message/InstallDatabaseRequest.java
  server/src/main/java/com/arcadedb/server/http/handler/PostServerCommandHandler.java
  server/src/test/java/com/arcadedb/server/ha/HTTP2ServersCreateReplicatedDatabaseIT.java
Labels: bug

#1795 fix: fixed broken HA test, reduced errors in console on HA replication
  server/src/main/java/com/arcadedb/server/http/handler/AbstractServerHttpHandler.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerLeaderChanges3TimesIT.java
Labels: bug

#1804 improve security: add sha to gihub actions
  .github/workflows/meterian.yml
  .github/workflows/mvn-deploy.yml
  .github/workflows/mvn-release.yml
  .github/workflows/mvn-test.yml
Labels: security
