Repository ArcadeData/arcadedb, pull requests merged in 2024-11, with the labels that each got.

#1805 Fix "NULL IN [NULL]"
  engine/src/main/java/com/arcadedb/query/sql/parser/InCondition.java
Labels: bug

#1808 Review Codacy and Jacoco Configuration
  .github/workflows/mvn-test.yml
  coverage/pom.xml
  integration/src/test/java/com/arcadedb/integration/backup/FullBackupIT.java
  pom.xml
Labels: enhancement

#1821 README Update for Java17
  README.md
Labels: documentation
