Repository ArcadeData/arcadedb, pull requests merged in 2025-05, with the labels that each got.

#2199 build: restructure CI workflow for improved build and test stages
  .github/workflows/mvn-test.yml
  engine/src/main/java/com/arcadedb/database/LocalDatabase.java
  pom.xml
Labels: do not merge

#2222 feat: encrypted backup and restore
  engine/src/main/grammar/SQLGrammar.jjt
  engine/src/main/java/com/arcadedb/query/sql/parser/BackupDatabaseStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/SqlParser.java
  integration/src/main/java/com/arcadedb/integration/backup/Backup.java
  integration/src/main/java/com/arcadedb/integration/backup/BackupSettings.java
  integration/src/main/java/com/arcadedb/integration/backup/format/FullBackupFormat.java
  integration/src/main/java/com/arcadedb/integration/restore/RestoreSettings.java
  integration/src/main/java/com/arcadedb/integration/restore/format/FullRestoreFormat.java
  integration/src/test/java/com/arcadedb/integration/backup/BackupDatabaseTest.java
  integration/src/test/java/com/arcadedb/integration/backup/FullBackupIT.java
Labels: enhancement

#2228 Iterable graph
  engine/src/main/java/com/arcadedb/graph/GraphEngine.java
  engine/src/main/java/com/arcadedb/graph/ImmutableVertex.java
  engine/src/main/java/com/arcadedb/graph/IterableGraph.java
  engine/src/main/java/com/arcadedb/graph/MutableVertex.java
  engine/src/main/java/com/arcadedb/graph/SynchronizedVertex.java
  engine/src/main/java/com/arcadedb/graph/Vertex.java
  engine/src/main/java/com/arcadedb/utility/MultiIterator.java
  network/src/main/java/com/arcadedb/remote/RemoteImmutableVertex.java
  network/src/main/java/com/arcadedb/remote/RemoteMutableVertex.java
  network/src/main/java/com/arcadedb/remote/RemoteVertex.java
Labels: enhancement

#2229 fix: fixed Postgres driver CPU 100%
  postgresw/src/main/java/com/arcadedb/postgres/PostgresNetworkExecutor.java
  postgresw/src/test/java/com/arcadedb/postgres/PostgresWJdbcTest.java
Labels: performance
