Repository ArcadeData/arcadedb, pull requests merged in 2025-08, with the labels that each got.

#2433 Fixes for a couple of issues discovered with vector support
  engine/src/main/java/com/arcadedb/query/sql/function/vector/SQLFunctionVectorNeighbors.java
  integration/src/main/java/com/arcadedb/integration/importer/vector/TextEmbeddingsImporter.java
  integration/src/test/java/com/arcadedb/integration/importer/FastTextVectorImportTest.java
  integration/src/test/resources/cc.en.300.small.vec.gz
Labels: bug

#2442 chore(studio-deps)(deps): bump the security-critical group across 1 d…
  e2e-studio/tests/datatables-compatibility.spec.ts
  e2e-studio/tests/datatables-critical-validation.spec.ts
  e2e-studio/tests/datatables-upgrade-validation.spec.ts
  e2e-studio/tests/debug-datatables-version.spec.ts
  e2e-studio/utils/test-utils.ts
  studio/package-lock.json
  studio/package.json
  studio/src/main/resources/static/css/studio.css
  studio/src/main/resources/static/index.html
  studio/src/main/resources/static/js/studio-table.js
  studio/webpack.config.js
Labels: javascript, studio, frontend

#2441 fix package.json studio version
  studio/package-lock.json
  studio/package.json
Labels: javascript, frontend

#2437 [Helm] Adding support for plugins configuration
  k8s/helm/Chart.yaml
  k8s/helm/templates/_helpers.tpl
  k8s/helm/templates/service.yaml
  k8s/helm/templates/statefulset.yaml
  k8s/helm/values.yaml
Labels: enhancement, docker
