Repository ArcadeData/arcadedb, pull requests merged in 2025-02, with the labels that each got.

#1959 #1956 fix PGSQL when used with JS/npm pg driver
  e2e/src/test/java/com/arcadedb/e2e/JdbcQueriesTest.java
  engine/src/main/java/com/arcadedb/database/Binary.java
  postgresw/src/main/java/com/arcadedb/postgres/PostgresNetworkExecutor.java
  postgresw/src/main/java/com/arcadedb/postgres/PostgresNetworkListener.java
  postgresw/src/main/java/com/arcadedb/postgres/PostgresPortal.java
  postgresw/src/main/java/com/arcadedb/postgres/PostgresType.java
  postgresw/src/test/java/com/arcadedb/postgres/PostgresWJdbcTest.java
Labels: bug, fixed

#1978 In STUDIO, if there is 4 or less character selected, ignore it and just send the whole editor query
  studio/src/main/resources/static/js/studio-database.js
Labels: enhancement

#2003 Fix inconsistent naming HSNW to HNSW
  engine/src/main/java/com/arcadedb/index/vector/HnswVectorIndex.java
  engine/src/main/java/com/arcadedb/query/sql/parser/CreateIndexStatement.java
  engine/src/main/java/com/arcadedb/schema/LocalSchema.java
  engine/src/main/java/com/arcadedb/schema/Schema.java
  engine/src/main/java/com/arcadedb/schema/VectorIndexBuilder.java
Labels: bug

#1990 #1989 fix failing IT tests
  e2e/src/test/java/com/arcadedb/e2e/RemoteDatabaseJavaApiTest.java
  e2e/src/test/java/com/arcadedb/e2e/RemoteDatabaseQueriesTest.java
  engine/src/main/java/com/arcadedb/database/BaseDocument.java
  engine/src/main/java/com/arcadedb/database/DetachedDocument.java
  engine/src/main/java/com/arcadedb/database/Document.java
  engine/src/main/java/com/arcadedb/query/sql/executor/CreateEdgesStep.java
  engine/src/main/java/com/arcadedb/query/sql/executor/ResultInternal.java
  engine/src/main/java/com/arcadedb/query/sql/executor/SelectExecutionPlanner.java
  engine/src/main/java/com/arcadedb/query/sql/parser/Projection.java
  engine/src/main/java/com/arcadedb/serializer/JsonGraphSerializer.java
  engine/src/main/java/com/arcadedb/serializer/JsonSerializer.java
  engine/src/test/java/com/arcadedb/event/RecordEncryptionTest.java
  engine/src/test/java/com/arcadedb/query/sql/executor/CreatePropertyStatementExecutionTest.java
  engine/src/test/java/com/arcadedb/serializer/BinarySerializerTest.java
  engine/src/test/java/com/arcadedb/serializer/JsonGraphSerializerTest.java
  engine/src/test/java/com/arcadedb/serializer/JsonSerializerTest.java
  gremlin/src/test/java/com/arcadedb/server/gremlin/AbstractGremlinServerIT.java
  gremlin/src/test/java/com/arcadedb/server/gremlin/RemoteGremlinFactoryIT.java
  integration/src/main/java/com/arcadedb/integration/exporter/format/JsonlExporterFormat.java
  integration/src/test/java/com/arcadedb/integration/backup/FullBackupIT.java
  pom.xml
  server/src/main/java/com/arcadedb/server/http/handler/AbstractQueryHandler.java
  server/src/test/java/com/arcadedb/server/BaseGraphServerTest.java
  server/src/test/java/com/arcadedb/server/HTTPGraphIT.java
  server/src/test/java/com/arcadedb/server/RemoteDateIT.java
  server/src/test/java/com/arcadedb/server/StaticBaseServerTest.java
  server/src/test/java/com/arcadedb/server/ha/HARandomCrashIT.java
  server/src/test/java/com/arcadedb/server/ha/HASplitBrainIT.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationChangeSchemaIT.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerIT.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerQuorumMajority2ServersOutIT.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerReplicaHotResyncIT.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerWriteAgainstReplicaIT.java
Labels: bug

#2015 refactor test reporting in CI workflow for unit and IT tests
  .github/workflows/mvn-test.yml
Labels: enhancement

#1539 Delete reuse space
  engine/src/main/java/com/arcadedb/GlobalConfiguration.java
  engine/src/main/java/com/arcadedb/database/TransactionContext.java
  engine/src/main/java/com/arcadedb/engine/LocalBucket.java
  engine/src/main/java/com/arcadedb/graph/EdgeLinkedList.java
  engine/src/main/java/com/arcadedb/graph/EdgeSegment.java
  engine/src/main/java/com/arcadedb/graph/GraphEngine.java
  engine/src/main/java/com/arcadedb/graph/ImmutableEdge.java
  engine/src/main/java/com/arcadedb/graph/MutableEdge.java
  engine/src/main/java/com/arcadedb/graph/MutableEdgeSegment.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndexCompactor.java
  engine/src/main/java/com/arcadedb/query/sql/parser/CheckDatabaseStatement.java
  engine/src/main/java/com/arcadedb/schema/LocalSchema.java
  engine/src/test/java/com/arcadedb/ACIDTransactionTest.java
  engine/src/test/java/com/arcadedb/AsyncTest.java
  engine/src/test/java/com/arcadedb/CRUDTest.java
  engine/src/test/java/com/arcadedb/RandomTestMultiThreadsTest.java
  engine/src/test/java/com/arcadedb/database/CheckDatabaseTest.java
  engine/src/test/java/com/arcadedb/engine/RandomDeleteTest.java
  engine/src/test/java/com/arcadedb/engine/RecordRecyclingTest.java
  engine/src/test/java/com/arcadedb/graph/InsertGraphIndexTest.java
  engine/src/test/java/com/arcadedb/graph/TestVertexDelete.java
  engine/src/test/java/com/arcadedb/index/LSMTreeIndexTest.java
Labels: enhancement

#2016 add release types and bluesky to README
  README.md
Labels: documentation
