Repository ArcadeData/arcadedb, pull requests merged in 2025-04, with the labels that each got.

#2113 Fixes columns with null values not being returned by pg driver | closes #2110
  postgresw/src/main/java/com/arcadedb/postgres/PostgresNetworkExecutor.java
Labels: enhancement

#2125 Wipeout freespace
  engine/src/main/java/com/arcadedb/database/Binary.java
  engine/src/main/java/com/arcadedb/database/BinaryStructure.java
  engine/src/main/java/com/arcadedb/database/TransactionContext.java
  engine/src/main/java/com/arcadedb/engine/DatabaseChecker.java
  engine/src/main/java/com/arcadedb/engine/LocalBucket.java
  engine/src/main/java/com/arcadedb/engine/MutablePage.java
Labels: performance

#2123 replace httpUrlConnection with HttpClient on RemoteHttpComponent
  e2e/src/test/java/com/arcadedb/e2e/JdbcQueriesTest.java
  e2e/src/test/java/com/arcadedb/e2e/RemoteDatabaseJavaApiTest.java
  network/src/main/java/com/arcadedb/remote/RemoteDatabase.java
  network/src/main/java/com/arcadedb/remote/RemoteHttpComponent.java
  network/src/main/java/com/arcadedb/remote/RemoteServer.java
  network/src/test/java/com/arcadedb/remote/RemoteDatabaseHttpIT.java
  network/src/test/java/com/arcadedb/remote/RemoteServerHttpIT.java
  server/src/main/java/com/arcadedb/server/http/HttpServer.java
  server/src/main/java/com/arcadedb/server/http/HttpSession.java
Labels: performance

#2129 Fix JSONTest
  engine/src/test/java/com/arcadedb/serializer/json/JSONTest.java
Labels: test

#2146 #2119 test: add parameterized query tests for JdbcQueries and psycopg2
  e2e-python/tests/test_arcadedb.py
  e2e/src/test/java/com/arcadedb/e2e/JdbcQueriesTest.java
Labels: enhancement

#2147 Add note about docker image rebuilding
  CONTRIBUTING.md
Labels: documentation

#2148 #1996 feat: add maven deploy plugin configurations for full, minimal,…
  package/pom.xml
Labels: fixed
