Repository ArcadeData/arcadedb, pull requests merged in 2025-09, with the labels that each got.

#2464 fix(PaginatedComponentFile): improve file renaming logic to handle co…
  engine/src/main/java/com/arcadedb/engine/PaginatedComponentFile.java
  engine/src/test/java/com/arcadedb/index/LSMTreeIndexCompactionTest.java
Labels: fixed / implemented

#2493 fix(pom.xml): explicitly import commons-lang3 to address CVE-2025-48924
  gremlin/pom.xml
Labels: dependencies, security, java

#2467 #2230 enhance variable behaviour in SQL script
  e2e/src/test/java/com/arcadedb/e2e/RemoteDatabaseJavaApiTest.java
  engine/src/main/java/com/arcadedb/query/sql/SQLScriptQueryEngine.java
  engine/src/main/java/com/arcadedb/query/sql/executor/BasicCommandContext.java
  engine/src/main/java/com/arcadedb/query/sql/executor/CommandContext.java
  engine/src/main/java/com/arcadedb/query/sql/executor/CreateEdgeExecutionPlanner.java
  engine/src/main/java/com/arcadedb/query/sql/executor/CreateVertexExecutionPlanner.java
  engine/src/main/java/com/arcadedb/query/sql/executor/DeleteExecutionPlanner.java
  engine/src/main/java/com/arcadedb/query/sql/executor/InsertExecutionPlanner.java
  engine/src/main/java/com/arcadedb/query/sql/executor/SelectExecutionPlanner.java
  engine/src/main/java/com/arcadedb/query/sql/parser/CreateIndexStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/CreatePropertyStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/CreateTypeAbstractStatement.java
  engine/src/main/java/com/arcadedb/schema/TypeIndexBuilder.java
  engine/src/test/java/com/arcadedb/query/sql/BatchTest.java
  engine/src/test/java/com/arcadedb/query/sql/DDLTest.java
  engine/src/test/java/com/arcadedb/query/sql/parser/BatchScriptTest.java
Labels: enhancement, high_priority, wip

#2502 feat(logging): replace SLF4J logger with LogManager for consistent lo…
  grpc-client/src/main/java/com/arcadedb/remote/grpc/RemoteGrpcDatabase.java
  grpc-client/src/main/java/com/arcadedb/remote/grpc/StreamingResultSet.java
  grpc-client/src/main/java/com/arcadedb/remote/grpc/utils/ProtoUtils.java
  grpcw/src/main/java/com/arcadedb/server/grpc/ArcadeDbGrpcService.java
  grpcw/src/main/java/com/arcadedb/server/grpc/CompressionAwareService.java
  grpcw/src/main/java/com/arcadedb/server/grpc/GrpcAuthInterceptor.java
  grpcw/src/main/java/com/arcadedb/server/grpc/GrpcCompressionInterceptor.java
  grpcw/src/main/java/com/arcadedb/server/grpc/GrpcLoggingInterceptor.java
  grpcw/src/main/java/com/arcadedb/server/grpc/GrpcMetricsInterceptor.java
  grpcw/src/main/java/com/arcadedb/server/grpc/GrpcServerPlugin.java
Labels: enhancement

#2523 fix: consistent http repsonses
  server/src/main/java/com/arcadedb/server/http/handler/AbstractServerHttpHandler.java
  server/src/main/java/com/arcadedb/server/http/handler/GetDatabasesHandler.java
  server/src/main/java/com/arcadedb/server/http/handler/GetServerHandler.java
  server/src/main/java/com/arcadedb/server/http/handler/PostServerCommandHandler.java
Labels: enhancement

#2541 chore: update license headers to Apache-2.0
  e2e-js/package-lock.json
  e2e-js/package.json
  e2e-studio/fixtures/test-fixtures.ts
  e2e-studio/global-setup.ts
  e2e-studio/global-teardown.ts
  e2e-studio/package-lock.json
  e2e-studio/package.json
  e2e-studio/playwright.config.ts
  e2e-studio/tests/create-database.spec.ts
  e2e-studio/tests/cytoscape-validation.spec.ts
  e2e-studio/tests/datatables-compatibility.spec.ts
  e2e-studio/tests/datatables-critical-validation.spec.ts
  e2e-studio/tests/datatables-upgrade-validation.spec.ts
  e2e-studio/tests/debug-datatables-version.spec.ts
  e2e-studio/tests/graph-context-menu.spec.ts
  e2e-studio/tests/graph-export.spec.ts
  e2e-studio/tests/graph-performance.spec.ts
  e2e-studio/tests/graph-styling.spec.ts
  e2e-studio/tests/notification-test.spec.ts
  e2e-studio/tests/query-beer-database.spec.ts
  e2e-studio/types/global.d.ts
  e2e-studio/utils/example-usage.ts
  e2e-studio/utils/index.ts
  e2e-studio/utils/test-config.ts
  e2e-studio/utils/test-utils.ts
Labels: documentation
