Repository ArcadeData/arcadedb, pull requests merged in 2025-03, with the labels that each got.

#2022 New `check database compress` sql command to compress the database pages
  engine/src/main/grammar/SQLGrammar.jjt
  engine/src/main/java/com/arcadedb/database/Binary.java
  engine/src/main/java/com/arcadedb/database/ImmutableDocument.java
  engine/src/main/java/com/arcadedb/engine/DatabaseChecker.java
  engine/src/main/java/com/arcadedb/engine/LocalBucket.java
  engine/src/main/java/com/arcadedb/graph/EdgeLinkedList.java
  engine/src/main/java/com/arcadedb/graph/GraphEngine.java
  engine/src/main/java/com/arcadedb/index/vector/HnswVectorIndex.java
  engine/src/main/java/com/arcadedb/query/sql/parser/CheckDatabaseStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/RebuildIndexStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/SqlParser.java
  engine/src/main/java/com/arcadedb/query/sql/parser/SqlParserConstants.java
  engine/src/main/java/com/arcadedb/query/sql/parser/SqlParserTokenManager.java
  engine/src/test/java/com/arcadedb/database/CompressDatabaseTest.java
  server/src/main/java/com/arcadedb/server/http/handler/AbstractQueryHandler.java
Labels: enhancement

#2033 Fixes possible code injection reported in #1780
  gremlin/src/main/java/org/opencypher/gremlin/translation/groovy/StringTranslationUtils.java
Labels: bug, security

#2035 perf: use the first space found instead of the best
  engine/src/main/java/com/arcadedb/engine/LocalBucket.java
Labels: performance

#2017 Enhance PostgresType to support array types (serialization, not deserialization)
  postgresw/src/main/java/com/arcadedb/postgres/PostgresNetworkExecutor.java
  postgresw/src/main/java/com/arcadedb/postgres/PostgresType.java
Labels: enhancement

#2040 replace test identities with albert einstein
  console/src/test/java/com/arcadedb/console/RemoteConsoleIT.java
  engine/src/main/java/com/arcadedb/GlobalConfiguration.java
  package/src/main/config/arcadedb-statefulset.yaml
  server/src/test/java/com/arcadedb/remote/RemoteDatabaseIT.java
  server/src/test/java/com/arcadedb/server/ServerDefaultDatabasesIT.java
  server/src/test/java/com/arcadedb/server/ServerImportDatabaseIT.java
  server/src/test/java/com/arcadedb/server/ServerReadOnlyDatabasesIT.java
  server/src/test/java/com/arcadedb/server/ServerRestoreDatabaseIT.java
  server/src/test/java/com/arcadedb/server/security/ServerProfilingIT.java
Labels: refactoring

#2042 Update tests
  console/src/test/java/com/arcadedb/console/ConsoleTest.java
  console/src/test/java/com/arcadedb/console/RemoteConsoleIT.java
  engine/src/test/java/com/arcadedb/query/select/SelectIndexExecutionTest.java
Labels: documentation

#2037 Initial impl of helm chart
  k8s/helm/Chart.yaml
  k8s/helm/README.md
  k8s/helm/index.yaml
  k8s/helm/templates/NOTES.txt
  k8s/helm/templates/_helpers.tpl
  k8s/helm/templates/extra-manifests.yaml
  k8s/helm/templates/hpa.yaml
  k8s/helm/templates/ingress.yaml
  k8s/helm/templates/secret.yaml
  k8s/helm/templates/service.yaml
  k8s/helm/templates/serviceaccount.yaml
  k8s/helm/templates/statefulset.yaml
  k8s/helm/values.yaml
Labels: enhancement

#2056 Add toJson and toMap to Remote Vertex and Edge
  network/src/main/java/com/arcadedb/remote/RemoteHttpComponent.java
  network/src/main/java/com/arcadedb/remote/RemoteImmutableEdge.java
  network/src/main/java/com/arcadedb/remote/RemoteImmutableVertex.java
  server/src/test/java/com/arcadedb/server/security/ServerProfilingIT.java
Labels: bug

#2074 #2061 enhance type mapping form ArcadeDB to Postgres protocol
  e2e-js/src/js-pg-e2e.test.js
  e2e-python/tests/test_arcadedb.py
  e2e/pom.xml
  e2e/src/test/java/com/arcadedb/e2e/JdbcQueriesTest.java
  engine/src/main/java/com/arcadedb/schema/LocalDocumentType.java
  engine/src/main/java/com/arcadedb/schema/Type.java
  engine/src/main/java/com/arcadedb/serializer/BinaryTypes.java
  engine/src/test/java/com/arcadedb/query/sql/executor/AlterPropertyExecutionTest.java
  postgresw/src/main/java/com/arcadedb/postgres/PostgresNetworkExecutor.java
  postgresw/src/main/java/com/arcadedb/postgres/PostgresType.java
  postgresw/src/test/java/com/arcadedb/postgres/PostgresWJdbcTest.java
Labels: bug

#2082 #2081 upgrade JDK from 17 to 21 in build configurations and Dockerfile
  .github/workflows/mvn-deploy.yml
  .github/workflows/mvn-release.yml
  .github/workflows/mvn-test.yml
  package/src/main/docker/Dockerfile
  pom.xml
Labels: enhancement

#2095 #2081 fix readme
  CONTRIBUTING.md
  README.md
Labels: fixed

#2096 Issue 2092
  engine/src/main/java/com/arcadedb/query/sql/executor/FetchFromIndexStep.java
  engine/src/main/java/com/arcadedb/query/sql/executor/FilterStep.java
  engine/src/main/java/com/arcadedb/query/sql/executor/GetValueFromIndexEntryStep.java
  engine/src/main/java/com/arcadedb/query/sql/executor/GlobalLetQueryStep.java
  engine/src/main/java/com/arcadedb/query/sql/executor/IndexSearchDescriptor.java
  engine/src/main/java/com/arcadedb/query/sql/executor/IndexSearchInfo.java
  engine/src/main/java/com/arcadedb/query/sql/executor/SelectExecutionPlan.java
  engine/src/main/java/com/arcadedb/query/sql/executor/SelectExecutionPlanner.java
  engine/src/main/java/com/arcadedb/query/sql/parser/BetweenCondition.java
  engine/src/main/java/com/arcadedb/query/sql/parser/BinaryCompareOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/BinaryCondition.java
  engine/src/main/java/com/arcadedb/query/sql/parser/BooleanExpression.java
  engine/src/main/java/com/arcadedb/query/sql/parser/ContainsAnyCondition.java
  engine/src/main/java/com/arcadedb/query/sql/parser/ContainsCondition.java
  engine/src/main/java/com/arcadedb/query/sql/parser/ContainsKeyOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/ContainsTextCondition.java
  engine/src/main/java/com/arcadedb/query/sql/parser/ContainsValueCondition.java
  engine/src/main/java/com/arcadedb/query/sql/parser/ContainsValueOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/CreateEdgeStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/EqualsCompareOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/Expression.java
  engine/src/main/java/com/arcadedb/query/sql/parser/GeOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/GtOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/ILikeOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/InCondition.java
  engine/src/main/java/com/arcadedb/query/sql/parser/InOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/IsNullCondition.java
  engine/src/main/java/com/arcadedb/query/sql/parser/LeOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/LikeOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/LtOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/NeOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/NearOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/NeqOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/NullSafeEqualsCompareOperator.java
  engine/src/main/java/com/arcadedb/query/sql/parser/SelectStatement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/Statement.java
  engine/src/main/java/com/arcadedb/query/sql/parser/WithinOperator.java
  engine/src/main/java/com/arcadedb/serializer/BinaryComparator.java
  engine/src/test/java/com/arcadedb/query/sql/Issue1898Test.java
Labels: bug

#2100 fix: graphql support for embedded documents
  graphql/src/main/java/com/arcadedb/graphql/schema/GraphQLResultSet.java
  graphql/src/test/java/com/arcadedb/graphql/AbstractGraphQLTest.java
  graphql/src/test/java/com/arcadedb/graphql/GraphQLBasicTest.java
Labels: bug

#2102 feat: implemented new connection strategy "FIXED"
  network/src/main/java/com/arcadedb/remote/RemoteHttpComponent.java
  server/src/test/java/com/arcadedb/server/ha/ReplicationServerFixedClientConnectionIT.java
Labels: enhancement

#2115 Add globalConfiguration.resetAll in tests
  engine/src/main/java/com/arcadedb/query/sql/parser/CreateIndexStatement.java
  engine/src/test/java/com/arcadedb/engine/TestInsertAndSelectWithThreadBucketSelectionStrategy.java
  engine/src/test/java/com/arcadedb/query/sql/OrderByTest.java
  engine/src/test/java/com/arcadedb/query/sql/executor/UpdateStatementExecutionTest.java
  engine/src/test/java/com/arcadedb/query/sql/function/sql/SQLFunctionsTest.java
  server/src/test/java/com/arcadedb/server/RemoteQueriesIT.java
  server/src/test/java/com/arcadedb/server/SelectOrderTest.java
Labels: enhancement
