Repository ArcadeData/arcadedb, pull requests merged in 2025-01, with the labels that each got.

#1889 #1873 refactor code and add tests for CSV with big content on columns
  integration/src/main/java/com/arcadedb/integration/importer/ImporterSettings.java
  integration/src/main/java/com/arcadedb/integration/importer/format/CSVImporterFormat.java
  integration/src/main/java/com/arcadedb/integration/importer/format/RDFImporterFormat.java
  integration/src/test/java/com/arcadedb/integration/importer/CSVImporterIT.java
  integration/src/test/resources/importer-big-size.csv
Labels: bug

#1903 Changed default buckets per type to 1
  engine/src/main/java/com/arcadedb/GlobalConfiguration.java
  engine/src/main/java/com/arcadedb/query/sql/executor/SelectExecutionPlanner.java
  engine/src/test/java/com/arcadedb/ACIDTransactionTest.java
  engine/src/test/java/com/arcadedb/TransactionIsolationTest.java
  engine/src/test/java/com/arcadedb/query/sql/executor/ScriptExecutionTest.java
  engine/src/test/java/com/arcadedb/query/sql/executor/SelectStatementExecutionTest.java
Labels: enhancement

#1911 #1763 add specific test for issues, fix CreateEdgesStep
  engine/src/main/java/com/arcadedb/graph/GraphEngine.java
  engine/src/main/java/com/arcadedb/query/sql/executor/CreateEdgeExecutionPlanner.java
  engine/src/main/java/com/arcadedb/query/sql/executor/CreateEdgesStep.java
  engine/src/test/java/com/arcadedb/query/sql/executor/CreateEdgeStatementExecutionTest.java
Labels: bug

#1917 Fix code scanning alert no. 157: Insecure randomness
  engine/src/main/java/com/arcadedb/query/sql/function/math/SQLFunctionRandomInt.java
Labels: security

#1921 Potential fix for code scanning alert no. 115: Insecure randomness
  network/src/main/java/com/arcadedb/network/binary/SocketFactory.java
Labels: security

#1930 #1922 JSONL: importer, tests, fixes to exporter
  engine/src/main/java/com/arcadedb/database/DatabaseComparator.java
  engine/src/main/java/com/arcadedb/database/DatabaseFactory.java
  engine/src/main/java/com/arcadedb/database/JSONSerializer.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeFullTextIndex.java
  engine/src/main/java/com/arcadedb/index/lsm/LSMTreeIndex.java
  engine/src/main/java/com/arcadedb/schema/Schema.java
  engine/src/main/java/com/arcadedb/serializer/JsonGraphSerializer.java
  engine/src/main/java/com/arcadedb/serializer/json/JSONObject.java
  engine/src/test/java/com/arcadedb/database/DatabaseComparatorTest.java
  engine/src/test/java/com/arcadedb/serializer/json/JSONSerializerTest.java
  integration/src/main/java/com/arcadedb/integration/exporter/format/JsonlExporterFormat.java
  integration/src/main/java/com/arcadedb/integration/importer/Neo4jImporter.java
  integration/src/main/java/com/arcadedb/integration/importer/OrientDBImporter.java
  integration/src/main/java/com/arcadedb/integration/importer/SourceDiscovery.java
  integration/src/main/java/com/arcadedb/integration/importer/format/JsonlImporterFormat.java
  integration/src/main/java/com/arcadedb/integration/importer/format/RDFImporterFormat.java
  integration/src/main/java/com/arcadedb/integration/importer/vector/TextEmbeddingsImporter.java
  integration/src/test/java/com/arcadedb/integration/exporter/JsonlExporterIT.java
  integration/src/test/java/com/arcadedb/integration/exporter/SQLLocalExporterTest.java
  integration/src/test/java/com/arcadedb/integration/importer/JSONImporterIT.java
  integration/src/test/java/com/arcadedb/integration/importer/JsonLImporterIT.java
  integration/src/test/java/com/arcadedb/integration/importer/Neo4jImporterIT.java
  integration/src/test/java/com/arcadedb/integration/importer/OrientDBImporterIT.java
  integration/src/test/resources/arcadedb-export.jsonl.tgz
Labels: enhancement

#1938 #1937 fix content type of prometheus endpoint to text/plain
  metrics/src/main/java/com/arcadedb/metrics/prometheus/GetPrometheusMetricsHandler.java
  metrics/src/test/java/com/arcadedb/metrics/prometheus/PrometheusMetricsPluginAuthenticatedTest.java
  metrics/src/test/java/com/arcadedb/metrics/prometheus/PrometheusMetricsPluginNotAuthenticatedTest.java
  server/src/main/java/com/arcadedb/server/http/handler/ExecutionResponse.java
Labels: fixed
